# Usar una imagen base de Python 3.11
FROM python:3.11-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de requisitos e instalar las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script de la aplicación web


# Exponer el puerto en el que se ejecutará la aplicación de Streamlit
EXPOSE 

# Comando para ejecutar la aplicación de Streamlit cuando se inicie el contenedor
CMD ["streamlit", "run", "app_webs.py"]
