name: MLOps GKE
on: [push, pull_request]

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: 
      - name: Set up gcloud CLI and kubectl
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: 'latest'
          install_components: 'gke-gcloud-auth-plugin'
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} --zone ${{ vars.GKE_ZONE }} --project ${{ vars.GCP_PROJECT_ID  }}
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker

      - name: Build and Push API Docker Image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api-sinerror:latest .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api-sinerror:latest
      - name: Build and Push Web Docker Image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-web-sinerror:latest -f Dockerfile.web .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-web-sinerror:latest
      - name: Deploy to GKE 
        run: |
          kubectl apply -f api-deployment.yaml
          kubectl apply -f api-service.yaml
          kubectl apply -f web-deployment.yaml
          kubectl apply -f web-service.yaml
          